# 예외처리 (exception handling)

- **프로그램 오류**
    - 컴파일 에러 : 컴파일할 때 발생하는 에러
    - **런타임 에러** : 실행할 때 발생하는 에러
    - 논리적 에러 : 의도와 다르게 동작 (실행 시)
    
- **자바의 런타임 에러**
    - **에러(error)** : 프로그램 코드에 의해서 수습될 수 없는 **심각한 오류**
    - **예외(exception)** : 프로그램 코드에 의해서 수습될 수 있는 **다소 미약한 오류**
    - **에러는 어쩔 수 없지만, 예외는 처리하자**
    
- **예외처리의 정의와 목적**
    - 정의 : 프로그램 실행 시 발생할 수 있는 **예외의 발생에 대비한 코드를 작성**하는 것
    - 목적 : **프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것**
    
- **예외 클래스의 계층 구조**
    - **RuntimeExeption 클래스들** : **프로그래머의 실수로 발생**하는 예외 ← **예외처리 선택**
    - **Exception 클래스들** : 사용자의 실수와 같은 **외적인 요인에 의해 발생**하는 예외 ← **예외처리 필수**

### try-catch 문 (예외처리 구문)

```java
try {
        // 예외가 발생할 가능성이 있는 문장
    } catch (Exception1 e1) {
        // Exception1 이 발생할 경우, 처리하기 위한 문장
    } catch (Exception2 e2) {
        // Exception2 가 발생할 경우, 처리하기 위한 문장
    } // try-catch 문 종료

// try-catch 문 괄호 { } 생략 불가!
// try 블럭에서 예외가 발생하면, 발생한 예외를 처리할 catch 블럭을 찾는다.
// 첫번째 catch 블럭부터 순서대로 찾아 내려가며, 일치하는 블럭이 없으면 예외는 처리되지 않는다.
```

```java
System.out.println(1); // 1
System.out.println(2); // 2
try {
    System.out.println(3); // 3
    System.out.println(0/0); // <- Error 발생 !
    System.out.println(4); // <- 실행되지 않음 !
} catch (ArithmeticException ae) {
    ae.printStackTrace(); // java.lang.ArithmeticException: / by zero
                          //    at Exception.main(Exception.java:8)
    System.out.println("예외 메시지 : " + ae.getMessage()); // 예외 메시지 : / by zero
}
System.out.println("프로그램 정상 종료"); // 프로그램 정상 종료
```

- **try 블럭 내에서 예외가 발생한 경우**
    1. **예외가 발생하면 발생한 예외 타입의 객체가 생성**된다. 예외 객체에는 예외에 대한 정보가 들어있고, printStackTrace() 나 getMessage() 같은 메서드들을 통해서 정보를 가져올 수 있다.
        1. **printStackTrace()** → 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
        2. **getMessage()** → 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
    2. **발생한 예외 객체와 일치하는 catch 블럭이 있는지 확인**한다. 이때 발생한 예외 객체를 catch 블럭의 참조변수로 접근할 수 있다. (참조변수가 예외 객체를 가리킨다.)
    3. **일치하는 catch 블럭을 찾게 되면 그 catch 블럭 내의 문장을 수행**하고 전체 try-catch 문을 빠져나와서 그 다음 문장을 계속해서 수행한다. 만약 일치하는 catch 블럭을 찾지 못하면 예외는 처리되지 못한다. (비정상적으로 프로그램 종료)
    4. **예외의 최고 조상인 Exception** 을 처리하는 catch 블럭은 **모든 종류의 예외를 처리**할 수 있기 때문에 **반드시 마지막 catch 블럭에 작성**한다. (위에 작성하면 Exception 블럭이 다 처리해버리기 때문에)
    
- **try 블럭 내에서 예외가 발생하지 않은 경우**
    - catch 블럭을 거치지 않고 전체 try-catch 문을 빠져나가서 수행을 계속한다.
    
- **멀티 catch 블럭**
    - 내용이 같은 catch 블럭을 하나로 합친 것 (JDK 1.7 부터)
    - 부모-자식 관계의 catch 블럭은 사용 X, 부모 타입의 참조변수가 선언된 catch 블럭만 사용하면 됨
    - 공통으로 갖고 있는 것만 참조변수로 사용 가능함
